### ISSUE TITLE
[Feature request] allow user to disable "Use B/W fg/bg when very close to B/W"

### ISSUE THREAD

**Issue by shaunsingh** [tecosaur/ox-chameleon#2]
While https://github.com/tecosaur/ox-chameleon/commit/f34becaf66d18481041cc52107b33d11b4dbde7e is very nice for printing documents, I find the background re-coloring to be annoying while working within emacs (the pure white hurts my eyes just a bit). 

It would be nice to allow the user to enable/disable this.

**Comment by tecosaur** [comment]
Ah yep, I'll add this. ETA a few days.

**Comment by tecosaur** [comment]
Done.

**Comment by shaunsingh** [comment]
Thanks!
