### ISSUE TITLE
latex export fails to render properly without additional config

### ISSUE THREAD

**Issue by hydrobeam** [tecosaur/ox-chameleon#5]
## Description of Issue
When trying to render a plain org file without any latex config, the export process doesn't succeed and looks like this:

![image](https://user-images.githubusercontent.com/70682032/188291044-e6790666-f846-43c5-827b-780e630c42be.png)
This is the original org file:
```
- Hello
- This is content
- This is more content
- This is, believe it or not, more content
\(\lambda + \lambda = \lambda\)

```
But, after pulling in `xcolor like so:

```
#+latex_header: \usepackage{xcolor}
```
the output looks a lot cleaner, but there's still some unexpected text (theme is `ef-spring`)

![image](https://user-images.githubusercontent.com/70682032/188291047-9c07849a-51f6-4cff-bf3c-7e348e190f42.png)
The first error in `Org PDF Latex Output` is:
```
! Undefined control sequence.
l.57 \addtokomafont
                 {title}{\color{documentTitle}}
```

So, I might be missing a koma-related class, but [running](https://tex.stackexchange.com/questions/115028/how-do-i-list-the-available-classes-in-my-installation) :
```
grep "\.cls" `kpsewhich --var-value TEXMFDIST`/ls-R > $HOME/allcls.txt
```
showed I had them all. So I started looking through teco's config for something koma related, and pasted the following: https://pastebin.com/NYuFY3Tr into my config, copied from: https://github.com/tecosaur/emacs-config/blob/master/config.org#class-templates

And the output worked as expected, with no extra text:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/70682032/188291524-873a427f-7e12-4422-9409-18143847e41b.png">

**Comment by tecosaur** [comment]
The readme has now been amended in a89ff0840efbfe2001351600a5383124a5b2234a.
